plugins: 
  - jest
env:
  browser: true
  es2021: true
  node: true
  jest/globals: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules: 
  no-console: 0
  import/extensions: 0
  no-restricted-syntax: off
  max-len: 0